.TH BTUN 1 "May 2015" btun\-0.1 "User Commands"
.SS NAME
.PP
btun \- bidirectional tunnel through a webbrowser
.SS SYNOPSIS
.PP
\f[B]btun\f[] [\f[B]\-d\f[]] [\f[B]\-l\f[] \f[I]local\f[]] [\f[B]\-s\f[]
\f[I]remote\f[]] [\f[B]\-t\f[] \f[I]tundev\f[]] [\f[B]\-p\f[]
\f[I]port\f[]][\f[B]\-b\f[] \f[I]bind_address\f[]] \f[I]keyfile\f[]
.PP
\f[B]btun\f[] [\f[B]\-v\f[]]
.SS DESCRIPTION
.PP
\f[B]btun\f[] establishes a bidirectional connection between two hosts
.PD 0
.P
.PD
using one or more browsers as mediators.
.IP
.nf
\f[C]
\ \ \ \ \ \ \ host1\ \ \ \ \ \ \ \ mediator\ \ \ \ \ \ \ host2
\ \ \ \ \ \ +\-\-\-\-\-\-+\ \ \ \ +\-\-\-\-\-\-\-\-\-+\ \ \ \ +\-\-\-\-\-\-+
\ \ +\-\-\-|\ btun\ |\-\-\-\-|\ browser\ |\-\-\-\-|\ btun\ |\-\-\-+
\ \ |\ \ \ +\-\-\-\-\-\-+\ \ \ \ +\-\-\-\-\-\-\-\-\-+\ \ \ \ +\-\-\-\-\-\-+\ \ \ |
\ tunX\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ tunX
\f[]
.fi
.PP
If multiple browsers are connected, every package is sent to all
.PD 0
.P
.PD
mediators.
The receiver takes the first package and drops the rest.
.SS OPTIONS
.PP
\f[B]\-d\f[]
.PD 0
.P
.PD
prints debug messages
.PP
\f[B]\-l\f[] \f[I]local\f[]
.PD 0
.P
.PD
sets the local address for a websocket connection.
If unspecified
.PD 0
.P
.PD
Javascript tries to guess an address.
This option has no effect
.PD 0
.P
.PD
if \f[B]\-s\f[] is not specified
.PP
\f[B]\-s\f[] \f[I]remote\f[]
.PD 0
.P
.PD
enables server mode: an index is delivered which connects the
.PD 0
.P
.PD
browser via websocket to \f[I]local\f[] and \f[I]remote\f[].
\f[I]local\f[] is guessed
.PD 0
.P
.PD
but can be set explicitly via the \f[B]\-l\f[] option.
.PP
\f[B]\-t\f[] \f[I]tundev\f[]
.PD 0
.P
.PD
sets the name of the tun device
.PP
\f[B]\-p\f[] \f[I]port\f[]
.PD 0
.P
.PD
sets the port.
Default: 8000.
.PP
\f[B]\-b\f[] \f[I]bind_address\f[]
.PD 0
.P
.PD
sets the bind address.
Default is to listen on all interfaces.
.SS EXAMPLES
.IP
.nf
\f[C]
host1\ #\ btun\ \-s\ ws://host2:8000\ keyfile.pem
host1\ #\ ifconfig\ tun0\ 10.0.111.1\ dstaddr\ 10.0.111.2

host2\ #\ btun\ keyfile.pem
host2\ #\ ifconfig\ tun0\ 10.0.111.2\ dstaddr\ 10.0.111.1
\f[]
.fi
.PP
Point your browser to <http://host1:8000>.
As long as the browser has a connection
.PD 0
.P
.PD
both hosts, the connection between both hosts is established.
.SS DIAGNOSTICS
.PP
Use tcpdump(1), the \f[B]\-d\f[] flag, and the debug tools of your
browser to debug
.PD 0
.P
.PD
network problems.
.SS BUGS
.PP
Currently \f[B]btun\f[] does not encrypt any data.
Both, a passive attacker
.PD 0
.P
.PD
and the mediator can read any data sent through btun.
